import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarExample from "../components/Navber";
import { SessionProvider } from "next-auth/react";
// Uncomment the ThemeProvider if you plan to use it
// import { ThemeProvider } from "../components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learning Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFF5EE]`}
      >
        <SessionProvider>
        {/* Navbar at the top */}
        <NavbarExample />

        {/* Uncomment the ThemeProvider if you're managing themes */}
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider> */}
        
        {/* Main content */}
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
